
-- Crear la base de datos
CREATE DATABASE salud_db;


-- Usar la base de datos
USE salud_db;


-- Crear la tabla de datos
CREATE TABLE VISTA_CONSOLIDADO (
    Localidad VARCHAR(255),
    Sexo ENUM('HOMBRE', 'MUJER', 'INTERSEXUAL', 'OTROS', 'NO REGISTRA'),
    Edad INT,
    Programa ENUM('PROGRAMA 1', 'PROGRAMA 2', 'PROGRAMA 3'),
    EAPB VARCHAR(255),
    Fecha_Atencion DATE
);


-- Crear la tabla POBLACION
CREATE TABLE POBLACION (
    ANO INT,
    CODIGO_LOCALIDAD INT,
    NOMBRE_LOCALIDAD VARCHAR(255),
    SEXO VARCHAR(50),
    EDAD INT,
    CURSODEVIDA VARCHAR(100),
    GRUPOEDAD VARCHAR(100),
    POBLACION_7 INT
);


-- Crear las tablas de los programa1
CREATE TABLE PROGRAMA_1 (
    REGIMEN_DE_AFILIACION VARCHAR(255),
    LOCALIDAD_CALCULADA VARCHAR(255),
    ASEGURADOR VARCHAR(255),
    FECHA_DE_NACIMIENTO_USUARIO VARCHAR(50), 
    SEXO VARCHAR(50),
    FECHA_DE_LA_CONSULTA VARCHAR(50), 
    NACIONALIDAD VARCHAR(100)
);


-- Crear las tablas de los programa2
CREATE TABLE PROGRAMA_2 (
    SEXO_BIOLOGICO VARCHAR(50),
    LOCALIDAD VARCHAR(255),
    EAPB VARCHAR(255),
    FECHA_DE_NACIMIENTO DATE,
    PERTENENCIA_ETNICA VARCHAR(100),
    SEXO_BIOLOGICO_1 VARCHAR(50),
    RIESGO_PSICOSOCIAL VARCHAR(50),
    FECHA_DE_LA_CONSULTA DATE,
    TALLA INT
);

ALTER TABLE PROGRAMA_2 MODIFY FECHA_DE_NACIMIENTO VARCHAR(20);
ALTER TABLE PROGRAMA_2 MODIFY FECHA_DE_LA_CONSULTA VARCHAR(20);
ALTER TABLE PROGRAMA_2 MODIFY TALLA INT NULL;


-- Crear las tablas de los programa3
CREATE TABLE PROGRAMA_3 (
    LOCALIDADFIC_3 VARCHAR(255),
    NACIONALIDAD_10 VARCHAR(100),
    NOMBREEAPB_27 VARCHAR(255),
    FECHADENACIMIENTO_14 DATE,
    ETNIA_18 VARCHAR(100),
    SEXO_11 VARCHAR(50),
    GENERO_12 VARCHAR(50),
    FECHAINTERVENCION_2 DATE
);


-- Crear las tablas de los programa4
CREATE TABLE PROGRAMA_4 (
    LOCALIDAD_FIC VARCHAR(255),
    ESTADO_CIVIL_ VARCHAR(50),
    NOMBRE_EAPB_ VARCHAR(255),
    FECHA_DE_NACIMIENTO_ DATE,
    ETNIA_ VARCHAR(100),
    SEXO_ VARCHAR(50),
    FECHA_INTERVENCION DATE
);





-- Cargar los datos en la tabla POBLACION
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.0/Uploads/POBLACION.txt'
INTO TABLE POBLACION
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(ANO, CODIGO_LOCALIDAD, NOMBRE_LOCALIDAD, SEXO, EDAD, CURSODEVIDA, GRUPOEDAD, POBLACION_7);


-- Cargar los datos en la tabla PROGRAMA_1
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.0/Uploads/archivo_limpio_sin_comillas.txt'
INTO TABLE PROGRAMA_1
FIELDS TERMINATED BY ','  
LINES TERMINATED BY '\n'
IGNORE 1 ROWS  
(REGIMEN_DE_AFILIACION, LOCALIDAD_CALCULADA, ASEGURADOR, FECHA_DE_NACIMIENTO_USUARIO, SEXO, FECHA_DE_LA_CONSULTA, NACIONALIDAD);


